src/main/java/com/cgi/osd/transactiondemo/persistence/model/Credentials.java
package com.cgi.osd.transactiondemo.persistence.model;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Created by tomasoberg on 2017-03-21.
 */

@Entity
@Table(name = "credentials")
@NamedQueries({@NamedQuery(name = "Credentials.findAll", query = "SELECT s FROM Credentials s order by s.lastname")})
public class Credentials extends EntityBase implements Serializable {

    @Id
    private static final long serialVersionUID = 1L;

    private String firstname;
    private String lastname;
    private Integer age;
    private String street;
    private String city;
    private Integer postalCode;
    private String email;
    private String phone;

    // TODO: Put these in a separate class?
    private String creditcard_payer;
    private String creditcard;


    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCreditcard_payer() {
        return creditcard_payer;
    }

    public String getCreditcard() {
        return creditcard;
    }

    public void setCreditcard_payer(String creditcard_payer) {
        this.creditcard_payer = creditcard_payer;
    }

    public void setCreditcard(String creditcard) {
        this.creditcard = creditcard;
    }

}

src/main/java/com/cgi/osd/transactiondemo/presentation/gui/BookingController.java
package com.cgi.osd.transactiondemo.presentation.gui;

import java.io.IOException;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.enterprise.context.SessionScoped;
import javax.annotation.PostConstruct;
import javax.interceptor.Interceptors;
import javax.inject.Inject;
import javax.inject.Named;

import com.cgi.osd.transactiondemo.logic.BookingService;
import com.cgi.osd.transactiondemo.logic.DTO.RestPaymentResponseDTO;
import com.cgi.osd.transactiondemo.logic.domainobject.*;
import com.cgi.osd.transactiondemo.logic.exception.PersistenceOperationException;
import com.cgi.osd.transactiondemo.persistence.ExceptionInterceptor;
import com.cgi.osd.transactiondemo.persistence.model.Transaction;
import com.cgi.osd.transactiondemo.util.AirportDOConverter;
import com.cgi.osd.transactiondemo.util.MailService;
import org.primefaces.event.FlowEvent;

/**
 * This class is responsible for the controller part of the MVC pattern for the booking process.
 */
@Named
@SessionScoped
public class BookingController implements Serializable {

    private static final long serialVersionUID = 1L;

    @Inject
    private BookingData bookingData;

    @Inject
    private BookingService bookingService;

    @Inject
    private AirportDOConverter airportDOConverter;

    @Inject
    private MailService mailService;

    @Inject
    private Logger logger;

    @Inject
    private FacesContext facesContext;

    Map<String, String> confirmationLetter = new HashMap<>();

    @PostConstruct
    private void init() {
        this.confirmationLetter.clear();
        bookingData.setCurrentDate(new Date());  // Sets the Date to now whenever page reloads
        final List<AirportDO> allAirports = bookingService.getAllAirports();
        bookingData.setAvailableAirports(allAirports);

        System.out.println("ADMIN");

        final List<BookingDO> allBookings = bookingService.getAllBookings();
        for (BookingDO b : allBookings) {
            System.out.println("Bokning: " + b.getCustomer());
        }

    }

    public String onFlowProcess(FlowEvent event) {
        // On every tab change that goes to seatTab, update all the seats array
        if (event.getNewStep().equals("seatTab")) {

            if (bookingData.getChosenFlight() == null) {
                FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Flight", "Choose a flight");
                facesContext.addMessage(null, msg);
                return event.getOldStep();
            }
            updateAllSeats();
        } else if (event.getNewStep().equals("credentialsTab")) {
            if (bookingData.getSelectedSeat() < 0) {

                FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "Seat", "Choose a seat");
                facesContext.addMessage(null, msg);

                return event.getOldStep();
            }
        }


        return event.getNewStep();
    }


    /**
     * Retrieves a list of seats from the DB and stores it in the seats field
     */
    public void updateAllSeats() {
        try {
            logger.fine("uppdaterar säten!");
            final List<SeatDO> seatsWithBookingsForFlight = bookingService.getSeatsWithBookingsForFlight(bookingData.getChosenFlight().getId());
            bookingData.setSeats(seatsWithBookingsForFlight);
        } catch (PersistenceOperationException e) {
            e.printStackTrace();
        }
    }

    public AirportDOConverter getAirportDOConverter() {
        return airportDOConverter;
    }


    public void setCurrentDate(Date date) {
        this.bookingData.setCurrentDate(date);
    }

    public Date getCurrentDate() {
        return this.bookingData.getCurrentDate();
    }

    public AirportDO getCurrentDeparture() {
        return bookingData.getCurrentDeparture();
    }

    public void setCurrentDeparture(AirportDO currentDeparture) {
        this.bookingData.setCurrentDeparture(currentDeparture);
    }

    public AirportDO getCurrentDestination() {
        return bookingData.getCurrentDestination();
    }

    public void setCurrentDestination(AirportDO destination) {
        bookingData.setCurrentDestination(destination);
    }

    public List<SeatDO> getSeats() {
        return this.bookingData.getSeats();
    }

    public CredentialsDO getCredentials() {
        return bookingData.getCredentials();
    }

    public void setCredentials(CredentialsDO credentials) {
        bookingData.setCredentials(credentials);
    }

    public int getSelectedSeat() {
        return bookingData.getSelectedSeat();
    }

    public void setSelectedSeat(int selectedSeat) {
        bookingData.setSelectedSeat(selectedSeat);
    }

    /**
     * Make a reservation for a seat number
     *
     * @param seatNr - integer, the seat to be reserved
     */
    public void reserve(int seatNr) {
        bookingData.setSelectedSeat(seatNr);
        FacesMessage msg = new FacesMessage("Seat", "Chosen seat :" + seatNr);
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }


    public List<FlightDO> getAvailableFlights() {
        return bookingData.getAvailableFlights();
    }

    public FlightDO getChosenFlight() {
        return bookingData.getChosenFlight();
    }

    public void setChosenFlight(FlightDO chosenFlight) {
        bookingData.setChosenFlight(chosenFlight);
    }

    public boolean reservedForFlight(int seatNr, int flight) {
        if (bookingData.getSeats() != null) {
            return bookingData.getSeats().get(seatNr - 1).getReservationStatusForFlight(flight);
        }
        return false;
    }

    @Interceptors(ExceptionInterceptor.class)
    public List<AirportDO> completeAirport(String query) {
        if (query == null)
            return null;

        List<AirportDO> airportDOS = null;


        try {
            airportDOS = bookingData.getAvailableAirports();
        } catch (Exception e) {
            FacesMessage fmMsg = new FacesMessage(FacesMessage.SEVERITY_ERROR, "System error", e.getClass().getName());
            FacesContext.getCurrentInstance().addMessage(null, fmMsg);
        }
        List<AirportDO> filteredAirportDOs = new ArrayList<>();
        for (AirportDO eachAirport : airportDOS) {
            if (eachAirport.getName().toLowerCase().startsWith(query.toLowerCase())) {
                filteredAirportDOs.add(eachAirport);
            }
        }
        return filteredAirportDOs;
    }

    public void updateAvailableFlights() {


        if (bookingData.getCurrentDeparture() == null) {
            FacesMessage msg = new FacesMessage("Travel", "Chose a departure");
            FacesContext.getCurrentInstance().addMessage(null, msg);
            logger.info("Departure is null");
            return;
        }

        if (bookingData.getCurrentDestination() == null) {
            FacesMessage msg = new FacesMessage("Travel", "Chosen a destination");
            FacesContext.getCurrentInstance().addMessage(null, msg);
            logger.info("Destination is null");
            return;
        }

        if (bookingData.getCurrentDate() == null) {
            FacesMessage msg = new FacesMessage("Travel", "Chosen a date");
            FacesContext.getCurrentInstance().addMessage(null, msg);
            logger.info("Date is null");
            return;

        }

        //---------------------------------------------------------------------
        // As JPQL doesn't support DATE() casting in its queries we need to
        // create an interval to search between instead. Therefore
        // today's date and time is taken and added 24 hours ahead and assigned
        // to the end of the range
        //---------------------------------------------------------------------

        Date date2 = bookingData.getCurrentDate();
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(bookingData.getCurrentDate());
        calendar.add(Calendar.HOUR_OF_DAY, 24);
        date2 = calendar.getTime();

        logger.info(String.valueOf(bookingData.getCurrentDate()));
        logger.info(" TILL: ");
        logger.info(String.valueOf(date2));

        List<FlightDO> availableFlights = bookingService.findFlightsBetweenDates(bookingData.getCurrentDeparture(), bookingData.getCurrentDestination(), bookingData.getCurrentDate(), date2);
        bookingData.setAvailableFlights(availableFlights);

    }

    public void book() {

        try {
            final CredentialsDO credentials = bookingData.getCredentials();
            final FlightDO chosenFlight = bookingData.getChosenFlight();
            final AirportDO currentDeparture = bookingData.getCurrentDeparture();
            final AirportDO currentDestination = bookingData.getCurrentDestination();


            //-----------------------------------------------------------------
            // Special case here, we just use the first four digits in the card
            // number for this special card service.
            //-----------------------------------------------------------------
            Transaction transaction = null;
            final String[] firstFourDigits = credentials.getCreditcard().split("-");
            if (firstFourDigits[0] != null) {

                int cardnumber = Integer.parseInt(firstFourDigits[0]);

                final RestPaymentResponseDTO restPaymentResponseDTO = bookingService.makePayment(
                        cardnumber,
                        credentials.getCreditcard_payer(),
                        chosenFlight.getPrice()
                );

                logger.info("RESULT: " + restPaymentResponseDTO);


                if (restPaymentResponseDTO == null) {
                    FacesMessage msg = new FacesMessage("Unsuccessful", " Transaction failed");
                    FacesContext.getCurrentInstance().addMessage(null, msg);

src/main/webapp/wizardflow/confirmationdetails.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <p:panel header="Confirmation">

        <p:messages></p:messages>
        <h:panelGrid id="confirmation" columns="3" columnClasses="grid,grid,grid">
            <h:panelGrid columns="2" columnClasses="label, value">
                <h:outputText value="Firstname: "/>
                <h:outputText value="#{bookingController.credentials.firstname}" styleClass="outputLabel"/>

                <h:outputText value="Lastname: "/>
                <h:outputText value="#{bookingController.credentials.lastname}" styleClass="outputLabel"/>

                <h:outputText value="Age: "/>
                <h:outputText value="#{bookingController.credentials.age}" styleClass="outputLabel"/>
            </h:panelGrid>

            <h:panelGrid columns="2" columnClasses="label, value">
                <h:outputText value="Street: "/>
                <h:outputText value="#{bookingController.credentials.street}" styleClass="outputLabel"/>

                <h:outputText value="Postal: "/>
                <h:outputText value="#{bookingController.credentials.postalCode}" styleClass="outputLabel"/>

                <h:outputText value="City: "/>
                <h:outputText value="#{bookingController.credentials.city}" styleClass="outputLabel"/>
            </h:panelGrid>

            <h:panelGrid columns="2" columnClasses="label, value">
                <h:outputText value="Email: "/>
                <h:outputText value="#{bookingController.credentials.email}" styleClass="outputLabel"/>

                <h:outputText value="Phone "/>
                <h:outputText value="#{bookingController.credentials.phone}" styleClass="outputLabel"/>

                <h:outputText/>
                <h:outputText/>
            </h:panelGrid>


            <h:panelGrid columns="2" columnClasses="label, value">
                <h:outputText value="Credit Card: "/>
                <h:outputText value="#{bookingController.credentials.creditcardFiltered()}"
                              styleClass="outputLabel"/>

                <h:outputText value="Payer "/>
                <h:outputText value="#{bookingController.credentials.creditcard_payer}"
                              styleClass="outputLabel"/>

                <h:outputText/>
                <h:outputText/>
            </h:panelGrid>


            <h:panelGrid columns="1" columnClasses="label, value">
                <h:outputText value="Seat nr: "/>
                <h:outputText value="#{bookingController.selectedSeat}" styleClass="outputLabel"/>

                <h:outputText/>
                <h:outputText/>
            </h:panelGrid>

        </h:panelGrid>

        <p:commandButton value="Submit" actionListener="#{bookingController.book}" update="bookingMessage" process="@this"/>


    </p:panel>


</ui:composition>

src/main/webapp/wizardflow/credentials.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <p:panel header="Personal Details">
        <p:messages />
            <h:panelGrid columns="2" columnClasses="label, value">
                <h:outputText value="Firstname: *" />
                <p:inputText value="#{bookingController.credentials.firstname}" required="true" label="Firstname" requiredMessage="First name required">
                </p:inputText>

                <h:outputText value="Lastname: *" />
                <p:inputText value="#{bookingController.credentials.lastname}" required="true" label="Lastname" requiredMessage="Last name required">
                </p:inputText>

                <h:outputText value="Street: "/>
                <p:inputText value="#{bookingController.credentials.street}"/>

                <h:outputText value="Postal Code: "/>
                <p:inputText value="#{bookingController.credentials.postalCode}" type="number" maxlength="5" />

                <h:outputText value="City: "/>
                <p:inputText value="#{bookingController.credentials.city}"  />

                <h:outputText value="Email: *"/>
                <p:inputText value="#{bookingController.credentials.email}" required="true" label="Email"
                             requiredMessage="email required"
                             validatorMessage="Invalid email address">
                    <f:validateRegex
                            pattern="^[a-zA-Z0-9.!#$%&amp;’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$"></f:validateRegex>
                </p:inputText>

                <h:outputText value="Phone: "/>
                <p:inputText value="#{bookingController.credentials.phone}"/>

            </h:panelGrid>

    </p:panel>

</ui:composition>

src/main/webapp/wizardflow/seatdetails.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <p:panel header="Seat Details">

        <p:messages autoUpdate="true" showDetail="true" />

        <h3 class="centeredColumn">Please choose a Seat</h3>
        <h:panelGrid styleClass="ui-g" id="panelGridForSeats" bodyrows="1" columns="2"
                     columnClasses="topAligned, topAligned">

            <p:panel id="details">
                <h:panelGrid columns="2" bodyrows="3" cellpadding="5">

                    <h:outputLabel value="Destination: "/>
                    <h:outputText value="#{bookingController.currentDestination.name}"/>

                    <h:outputLabel value="Chosen date: "/>
                    <h:outputText value="#{bookingController.currentDate}"/>

                    <h:outputLabel value="Chosen flight: "/>
                    <h:outputText value="#{bookingController.chosenFlight}"/>

                    <h:outputLabel value="Chosen seat: " for="chosenSeat" validatorMessage="Seat required" />

                    <h:outputText id="chosenSeat" value="#{bookingController.selectedSeat}"
                                  rendered="#{bookingController.selectedSeat gt 0}"/>
                    <h:outputText value=" " rendered="#{bookingController.selectedSeat lt 1}"/>

                    <h:outputLabel value="Price:" for="price"/>
                    <h:outputText id="price" value="#{bookingController.chosenFlight.price}"/>
                </h:panelGrid>
            </p:panel>

            <p:panel>
                <ui:repeat value="#{bookingController.seats}" var="seat">
                    <p:separator styleClass="separator" layout="block"
                                 rendered="#{(seat.seatNumber-1) % 5 == 0}"></p:separator>
                    <p:commandButton
                            styleClass="seat"
                            value="#{seat.seatNumber}"
                            disabled="#{ bookingController.reservedForFlight(seat.seatNumber, bookingController.chosenFlight.id) }">
                        <p:ajax update="@form:details"
                                listener="#{bookingController.reserve(seat.seatNumber)}"/>
                    </p:commandButton>
                </ui:repeat>
            </p:panel>
        </h:panelGrid>
    </p:panel>

</ui:composition>

src/main/webapp/wizardflow/traveldetails.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui">

    <p:panel header="Travel Details">
        <p:messages  autoUpdate="true" showDetail="true" />
        <h:panelGrid columns="2" columnClasses="topAligned, topAligned">
            <p:panel styleClass="topAligned">
                <p:outputPanel rendered="true"> 
                    <h:panelGrid columns="2" columnClasses="label, value">
                        <p:outputLabel value="From: " for="departure_airport" styleClass="fixedWidth"/>
                        <p:autoComplete id="departure_airport"
                                        value="#{bookingController.currentDeparture}"
                                        completeMethod="#{bookingController.completeAirport}"
                                        converter="#{bookingController.airportDOConverter}"
                                        var="ap"
                                        itemLabel="#{ap.name}"
                                        itemValue="#{ap}"
                                        forceSelection="true"
                                        required="true"

                                        validatorMessage="Validation failed"
                                        requiredMessage="Departure airport required"
                                        >

                            <p:ajax update="@this @form:flightsTable"
                                    oncomplete="#{bookingController.updateAvailableFlights()}"/>
                            />

                        </p:autoComplete>

                        <p:outputLabel value="To: " for="desination_airport"
                                       styleClass="fixedWidth"/>

                        <p:autoComplete id="desination_airport"
                                        value="#{bookingController.currentDestination}"
                                        completeMethod="#{bookingController.completeAirport}"
                                        converter="#{bookingController.airportDOConverter}"
                                        var="ap"
                                        itemLabel="#{ap.name}"
                                        itemValue="#{ap}"
                                        forceSelection="true"
                                        required="true"
                                        validatorMessage="Validation failed"
                                        requiredMessage="Destination airport required"
                                        >
                            <p:ajax update="@this @form:flightsTable"
                                    oncomplete="#{bookingController.updateAvailableFlights()}"/>
                        </p:autoComplete>


                    </h:panelGrid>


                </p:outputPanel>


                <p:outputPanel>
                    <p:calendar id="traveldate"
                                required="true"
                                validatorMessage="Departure date required"
                                value="#{bookingController.currentDate}"
                                label="Date"
                                mode="inline">

                        <p:ajax
                                event="dateSelect"
                                update="@form:flightsTable"
                                listener="#{bookingController.updateAvailableFlights}"/>
                    </p:calendar>
                </p:outputPanel>


            </p:panel>


            <p:panel>
                <p:dataTable id="flightsTable"
                             required="true"
                             emptyMessage="Choose a flight"
                             var="fl"
                             value="#{bookingController.availableFlights}"
                             selectionMode="single"
                             selection="#{bookingController.chosenFlight}"
                             rowKey="#{fl.id}">
                    <f:facet name="header">
                        Available Flights
                    </f:facet>
                    <p:column headerText="Flight Nr">
                        <h:outputText value="#{fl.id}"/>
                    </p:column>
                    <p:column headerText="Price">
                        <h:outputText value="#{fl.price}"/>
                    </p:column>
                    <p:column headerText="Departure">
                        <h:outputText value="#{fl.departureTimeFormatted}"/>
                    </p:column>
                    <p:column headerText="Arrival">
                        <h:outputText value="#{fl.arrivalTimeFormatted}"/>
                    </p:column>
                </p:dataTable>
            </p:panel>

        </h:panelGrid>
    </p:panel>

</ui:composition>